style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/treee111/wahooDeviceThemes
options:
  tag_filter_pattern: "^v"
  sort: "semver"
  commits:
    sort_by: "Scope"
    filters:
      Type:
        - HIGHWAY
        - POIs
        - CAPTION
        - STYLE
        - FIX
        - DEV
  commit_groups:
    sort_by: Custom
    title_order:
      - HIGHWAY
      - POIs
      - CAPTION
      - STYLE
      - FIX
      - DEV
    title_maps:
      HIGHWAY: highway/ - road, street or path
      POIs: Points of Interest
      CAPTION: Captions (text)
      STYLE: Styles, Outlines, etc.
      FIX: Bug Fixes
      DEV: Development/Infrastructure/Test/CI
  header:
    pattern: "^\\[(\\w*)\\]\\s(?:([^\\:]*)\\:\\s)?(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  issues:
    prefix:
      - "#"
  notes:
    keywords:
      - BREAKING CHANGE
